/* (Beta) Export of data model Streetlight of the subject dataModel.Streetlighting for a PostgreSQL database. Pending translation of enumerations and multityped attributes */
CREATE TYPE Streetlight_controllingMethod_type AS ENUM ('group', 'individual');
CREATE TYPE Streetlight_locationCategory_type AS ENUM ('bridge', 'centralIsland', 'facade', 'garden', 'park', 'parking', 'pedestrianPath', 'playground', 'road', 'sidewalk', 'tunnel');
CREATE TYPE Streetlight_powerState_type AS ENUM ('bootingUp', 'low', 'off', 'on');
CREATE TYPE Streetlight_status_type AS ENUM ('brokenLantern', 'columnIssue', 'defectiveLamp', 'ok');
CREATE TYPE Streetlight_type AS ENUM ('Streetlight');
CREATE TABLE Streetlight (
  "address" JSON,
  "alternateName" TEXT,
  "annotations" JSON,
  "areaServed" TEXT,
  "circuit" TEXT,
  "color" TEXT,
  "controllingMethod" Streetlight_controllingMethod_type,
  "current" NUMERIC,
  "dataProvider" TEXT,
  "dateCreated" TIMESTAMP,
  "dateLastLampChange" TIMESTAMP,
  "dateLastSwitchingOff" TIMESTAMP,
  "dateLastSwitchingOn" TIMESTAMP,
  "dateModified" TIMESTAMP,
  "dateServiceStarted" TIMESTAMP,
  "description" TEXT,
  "deviceInfo" JSON,
  "feederID" JSON,
  "feederPillarNum" TEXT,
  "id" TEXT PRIMARY KEY,
  "illuminanceLevel" NUMERIC,
  "image" TEXT,
  "lanternHeight" NUMERIC,
  "lifetimeMotionDetected" NUMERIC,
  "lifetimePowerConsumption" NUMERIC,
  "location" JSON,
  "locationCategory" Streetlight_locationCategory_type,
  "municipalityInfo" JSON,
  "name" TEXT,
  "observationDateTime" TIMESTAMP,
  "owner" JSON,
  "powerConsumption" NUMERIC,
  "powerFactor" NUMERIC,
  "powerRating" NUMERIC,
  "powerState" Streetlight_powerState_type,
  "refDevice" JSON,
  "refStreetlightControlCabinet" JSON,
  "refStreetlightGroup" JSON,
  "refStreetlightModel" JSON,
  "seeAlso" JSON,
  "source" TEXT,
  "status" Streetlight_status_type,
  "streetPoleNum" TEXT,
  "type" Streetlight_type,
  "voltage" NUMERIC
);